(defpackage %3b-tcod
  (:use :cl #:cffi)
  (:local-nicknames (#:a #:alexandria-2))
  (:export
   #:line
   #:line-init-mt
   #:line-step-mt
   #:bsp-new
   #:bsp-new-with-size
   #:bsp-delete
   #:bsp-left
   #:bsp-right
   #:bsp-father
   #:bsp-is-leaf
   #:bsp-traverse-pre-order
   #:bsp-traverse-in-order
   #:bsp-traverse-post-order
   #:bsp-traverse-level-order
   #:bsp-traverse-inverted-level-order
   #:bsp-contains
   #:bsp-find-node
   #:bsp-resize
   #:bsp-split-once
   #:bsp-split-recursive
   #:bsp-remove-sons
   ;;#:color-hsv
   ;;#:color-rgb
   #:color-equals
   #:color-add
   #:color-subtract
   #:color-multiply
   #:color-multiply-scalar
   #:color-lerp
   #:color-alpha-blend
   #:color-set-hsv
   #:color-get-hsv
   #:color-get-hue
   #:color-set-hue
   #:color-get-saturation
   #:color-set-saturation
   #:color-get-value
   #:color-set-value
   #:color-shift-hue
   #:color-scale-hsv
   #:color-gen-map
   #:console-new
   #:console-get-width
   #:console-get-height
   #:console-set-key-color
   #:console-blit
   #:console-blit-key-color
   #:console-delete
   #:console-set-default-background
   #:console-set-default-foreground
   #:console-clear
   #:console-set-char-background
   #:console-set-char-foreground
   #:console-set-char
   #:console-put-char
   #:console-put-char-ex
   #:console-set-background-flag
   #:console-get-background-flag
   #:console-set-alignment
   #:console-get-alignment
   #:console-get-default-background
   #:console-get-default-foreground
   #:console-get-char-background
   #:console-get-char-foreground
   #:console-get-char
   #:console-rect
   #:console-hline
   #:console-vline
   #:console-flush-ex
   #:console-flush
   #:console-from-file
   #:console-load-asc
   #:console-load-apf
   #:console-save-asc
   #:console-save-apf
   #:console-credits-reset
   #:console-credits-render-ex
   #:console-set-color-control
   #:console-printf
   #:console-printf-ex
   #:console-printf-rect
   #:console-printf-rect-ex
   #:console-printf-frame
   #:console-get-height-rect-fmt
   #:console-printn
   #:console-printn-rect
   #:console-get-height-rect-n
   #:console-get-height-rect-wn
   #:console-from-xp
   #:console-load-xp
   #:console-save-xp
   #:load-xp-from-memory
   #:save-xp-to-memory
   #:load-xp
   #:save-xp
   #:context-delete
   #:context-screen-pixel-to-tile-d
   #:context-screen-pixel-to-tile-i
   #:context-convert-event-coordinates
   #:context-save-screenshot
   #:context-get-sdl-window
   #:context-get-sdl-renderer
   #:context-change-tileset
   #:context-get-renderer-type
   #:context-recommended-console-size
   #:context-screen-capture
   #:context-screen-capture-alloc
   #:context-set-mouse-transform
   #:context-new
   #:get-error
   #:set-error
   #:set-errorf
   #:clear-error
   #:map-new
   #:map-clear
   #:map-copy
   #:map-set-properties
   #:map-delete
   #:map-compute-fov
   #:map-is-in-fov
   #:map-set-in-fov
   #:map-is-transparent
   #:map-is-walkable
   #:map-get-width
   #:map-get-height
   #:map-get-nb-cells
   #:heightmap-new
   #:heightmap-delete
   #:heightmap-get-value
   #:heightmap-get-interpolated-value
   #:heightmap-set-value
   #:heightmap-get-slope
   #:heightmap-get-normal
   #:heightmap-count-cells
   #:heightmap-has-land-on-border
   #:heightmap-get-minmax
   #:heightmap-copy
   #:heightmap-add
   #:heightmap-scale
   #:heightmap-clamp
   #:heightmap-normalize
   #:heightmap-clear
   #:heightmap-lerp-hm
   #:heightmap-add-hm
   #:heightmap-multiply-hm
   #:heightmap-add-hill
   #:heightmap-dig-hill
   #:heightmap-dig-bezier
   #:heightmap-rain-erosion
   #:heightmap-kernel-transform
   #:heightmap-add-voronoi
   #:heightmap-mid-point-displacement
   #:heightmap-add-fbm
   #:heightmap-scale-fbm
   #:image-new
   #:image-from-console
   #:image-refresh-console
   #:image-clear
   #:image-invert
   #:image-hflip
   #:image-rotate90
   #:image-vflip
   #:image-scale
   #:image-load
   #:image-save
   #:image-get-size
   #:image-get-pixel
   #:image-get-alpha
   #:image-get-mipmap-pixel
   #:image-put-pixel
   #:image-blit
   #:image-blit-rect
   #:image-blit-2x
   #:image-delete
   #:image-set-key-color
   #:image-is-pixel-transparent
   #:list-new
   #:list-allocate
   #:list-duplicate
   #:list-delete
   #:list-push
   #:list-pop
   #:list-peek
   #:list-add-all
   #:list-get
   #:list-set
   #:list-begin
   #:list-end
   #:list-reverse
   #:list-remove-iterator
   #:list-remove
   #:list-remove-iterator-fast
   #:list-remove-fast
   #:list-contains
   #:list-clear
   #:list-clear-and-delete
   #:list-size
   #:list-insert-before
   #:list-is-empty
   #:set-log-callback
   #:set-log-level
   #:random-get-instance
   #:random-new
   #:random-save
   #:random-restore
   #:random-new-from-seed
   #:random-delete
   #:random-set-distribution
   #:random-get-int
   #:random-get-float
   #:random-get-double
   #:random-get-int-mean
   #:random-get-float-mean
   #:random-get-double-mean
   #:random-dice-new
   #:random-dice-roll
   #:random-dice-roll-s
   #:namegen-parse
   #:namegen-generate
   #:namegen-generate-custom
   #:namegen-get-sets
   #:namegen-get-nb-sets-wrapper
   #:namegen-get-sets-wrapper
   #:namegen-destroy
   #:noise-new
   #:noise-set-type
   #:noise-get-ex
   #:noise-get-fbm-ex
   #:noise-get-turbulence-ex
   #:noise-get
   #:noise-get-fbm
   #:noise-get-turbulence
   #:noise-delete
   #:noise-get-vectorized
   #:noise-get-fbm-vectorized
   #:noise-get-turbulence-vectorized
   #:struct-get-name
   #:struct-add-property
   #:struct-add-list-property
   #:struct-add-value-list
   #:struct-add-value-list-sized
   #:struct-add-flag
   #:struct-add-structure
   #:struct-is-mandatory
   #:struct-get-type
   #:parser-new
   #:parser-new-struct
   #:parser-new-custom-type
   #:parser-run
   #:parser-delete
   #:parser-error
   #:parser-has-property
   #:parser-get-bool-property
   #:parser-get-char-property
   #:parser-get-int-property
   #:parser-get-float-property
   #:parser-get-string-property
   #:parser-get-color-property
   #:parser-get-dice-property-py
   #:parser-get-custom-property
   #:parser-get-list-property
   #:path-new-using-map
   #:path-new-using-function
   #:path-compute
   #:path-walk
   #:path-is-empty
   #:path-size
   #:path-reverse
   #:path-get
   #:path-get-origin
   #:path-get-destination
   #:path-delete
   #:dijkstra-new
   #:dijkstra-new-using-function
   #:dijkstra-compute
   #:dijkstra-get-distance
   #:dijkstra-path-set
   #:dijkstra-is-empty
   #:dijkstra-size
   #:dijkstra-reverse
   #:dijkstra-get
   #:dijkstra-path-walk
   #:dijkstra-delete
   #:pf-new
   #:pf-delete
   #:pf-set-distance-pointer
   #:pf-set-graph2d-pointer
   #:pf-set-traversal-pointer
   #:pf-recompile
   #:pf-compute
   #:pf-compute-step
   #:tileset-new
   #:tileset-delete
   #:tileset-load
   #:tileset-load-mem
   #:tileset-load-raw
   #:tileset-assign-tile
   #:tileset-get-tile
   #:load-bdf
   #:tileset-load-bdf-memory
   #:text-init
   #:text-init2
   #:text-set-pos
   #:text-set-properties
   #:text-set-colors
   #:text-update
   #:text-render
   #:text-get
   #:text-reset
   #:text-delete
   #:console-fill-background
   #:console-fill-foreground
   #:console-fill-char
   #:console-double-hline
   #:console-double-vline
   #:console-print-double-frame
   #:line-line
   #:console-is-fullscreen
   #:with-bsp-node
   #:context-present))

(defpackage 3b-tcod
  (:use :cl)
  (:local-nicknames (#:a #:alexandria-2)
                    (#:% #:%3b-tcod))
  (:import-from #:%3b-tcod
                ;; bresenham.h
                #:line
                ;; bsp.h
                #:bsp-new
                #:bsp-new-with-size
                #:bsp-left
                #:bsp-right
                #:bsp-father
                #:bsp-is-leaf
                #:bsp-traverse-pre-order
                #:bsp-traverse-in-order
                #:bsp-traverse-post-order
                #:bsp-traverse-level-order
                #:bsp-traverse-inverted-level-order
                #:bsp-contains
                #:bsp-find-node
                #:bsp-resize
                #:bsp-split-once
                #:bsp-split-recursive
                #:bsp-remove-sons
                ;; color.h
                #:color-equals
                #:color-add
                #:color-subtract
                #:color-multiply
                #:color-multiply-scalar
                #:color-lerp
                ;;#:color-alpha-blend
                ;;#:color-set-hsv
                #:color-get-hue
                #:color-get-saturation
                #:color-get-value
                ;; console.h
                #:console-new
                #:console-get-width
                #:console-get-height
                #:console-set-key-color
                #:console-blit
                #:console-delete
                #:console-set-default-background
                #:console-set-default-foreground
                #:console-clear
                #:console-set-char-background
                #:console-set-char-foreground
                #:console-set-background-flag
                #:console-get-background-flag
                #:console-set-alignment
                #:console-get-alignment
                #:console-get-default-background
                #:console-get-default-foreground
                #:console-get-char-background
                #:console-get-char-foreground
                #:console-get-char
                ;; console_drawing.h
                #:console-rect
                #:console-hline
                #:console-vline
                ;; console_etc.h
                #:console-flush
                #:console-from-file
                #:console-load-asc
                #:console-load-apf
                #:console-save-asc
                #:console-save-apf
                #:console-credits-reset
                #:console-credits-render-ex
                ;; console_init.h
                #:console-is-fullscreen
                ;; console_printing.h
                #:console-set-color-control
                #:console-get-height-rect-n
                #:console-get-height-rect-wn
                ;; console_rexpaint.h
                #:console-from-xp
                #:console-load-xp
                #:console-save-xp
                ;; context.h
                #:context-delete
                #:context-save-screenshot
                #:context-get-sdl-window
                #:context-get-sdl-renderer
                #:context-change-tileset
                ;; error.h
                #:get-error
                #:set-error
                #:clear-error
                ;; fov.h
                #:map-new
                #:map-clear
                #:map-copy
                #:map-set-properties
                #:map-delete
                #:map-compute-fov
                #:map-is-in-fov
                #:map-set-in-fov
                #:map-is-transparent
                #:map-is-walkable
                #:map-get-width
                #:map-get-height
                #:map-get-nb-cells
                ;; heightmap.h
                #:heightmap-new
                #:heightmap-delete
                #:heightmap-get-value
                #:heightmap-get-interpolated-value
                #:heightmap-set-value
                #:heightmap-get-slope
                #:heightmap-count-cells
                #:heightmap-has-land-on-border
                #:heightmap-copy
                #:heightmap-add
                #:heightmap-scale
                #:heightmap-clamp
                #:heightmap-normalize
                #:heightmap-clear
                #:heightmap-lerp-hm
                #:heightmap-add-hm
                #:heightmap-multiply-hm
                #:heightmap-add-hill
                #:heightmap-dig-hill
                #:heightmap-rain-erosion
                #:heightmap-add-fbm
                #:heightmap-scale-fbm
                ;; image.h
                #:image-new
                #:image-from-console
                #:image-refresh-console
                #:image-clear
                #:image-invert
                #:image-hflip
                #:image-rotate90
                #:image-vflip
                #:image-scale
                #:image-load
                #:image-save
                #:image-get-pixel
                #:image-get-alpha
                #:image-get-mipmap-pixel
                #:image-put-pixel
                #:image-blit
                #:image-blit-rect
                #:image-blit-2x
                #:image-delete
                #:image-set-key-color
                #:image-is-pixel-transparent
                ;; logging.h
                #:set-log-callback
                #:set-log-level
                ;;mersenne.h
                #:random-get-instance
                #:random-new
                #:random-save
                #:random-restore
                #:random-new-from-seed
                #:random-delete
                #:random-set-distribution
                #:random-get-int
                #:random-get-float
                #:random-get-double
                #:random-get-int-mean
                #:random-get-float-mean
                #:random-get-double-mean
                #:random-dice-roll-s
                #:namegen-parse

                ;; namegen.h
                #:namegen-parse
                #:namegen-destroy
                ;; noise.h
                #:noise-set-type
                #:noise-delete
                ;; path.h
                #:path-new-using-map
                #:path-new-using-function
                #:path-compute
                #:path-is-empty
                #:path-size
                #:path-reverse
                #:path-delete
                #:dijkstra-new
                #:dijkstra-new-using-function
                #:dijkstra-compute
                #:dijkstra-get-distance
                #:dijkstra-path-set
                #:dijkstra-is-empty
                #:dijkstra-size
                #:dijkstra-reverse
                #:dijkstra-delete
                ;; tileset.h
                #:tileset-new
                #:tileset-delete
                #:tileset-assign-tile
                ;; tileset_bdf.h
                #:load-bdf
                ;; txtfield.h
                #:text-init
                #:text-init2
                #:text-set-pos
                #:text-set-properties
                #:text-render
                #:text-get
                #:text-reset
                #:text-delete







                ;;

                #:noise-delete
                #:image-new
                #:image-put-pixel
                #:image-blit
                #:image-blit-2x
                #:image-blit-rect)

  (:export
   ;; bresenham.h
   #:line
   #:line-mt-delete
   #:line-mt-new
   #:with-line-mt
   ;; bsp.h
   #:bsp-new
   #:bsp-new-with-size
   #:bsp-left
   #:bsp-right
   #:bsp-father
   #:bsp-is-leaf
   #:bsp-traverse-pre-order
   #:bsp-traverse-in-order
   #:bsp-traverse-post-order
   #:bsp-traverse-level-order
   #:bsp-traverse-inverted-level-order
   #:bsp-contains
   #:bsp-find-node
   #:bsp-resize
   #:bsp-split-once
   #:bsp-split-recursive
   #:bsp-remove-sons
   ;; color.h
   #:color
   #:color-rgb
   #:color-hsv
   #:compose-color
   #:decompose-color
   #:color-equals
   #:color-add
   #:color-subtract
   #:color-multiply
   #:color-multiply-scalar
   #:color-lerp
   #:color-alpha-blend
   #:color-get-hsv
   #:color-get-hue
   #:color-get-saturation
   #:color-get-value
   #:color-set-hue
   #:color-set-saturation
   #:color-set-value
   #:color-shift-hue
   #:color-scale-hsv
   #:color-gen-map
   ;; console.h
   #:console-new
   #:console-get-width
   #:console-get-height
   #:console-set-key-color
   #:console-blit
   #:console-blit-key-color
   #:console-delete
   #:console-set-default-background
   #:console-set-default-foreground
   #:console-clear
   #:console-set-char-background
   #:console-set-char-foreground
   #:console-set-char
   #:console-put-char
   #:console-put-char-ex
   #:console-set-background-flag
   #:console-get-background-flag
   #:console-set-alignment
   #:console-get-alignment
   #:console-get-default-background
   #:console-get-default-foreground
   #:console-get-char-background
   #:console-get-char-foreground
   #:console-get-char
   ;; console_drawing.h
   #:console-rect
   #:console-hline
   #:console-vline
   ;; console_etc.h
   #:background-add-alpha
   #:background-alpha
   #:bkgnd-add-alpha
   #:bkgnd-alpha
   #:console-flush-ex
   #:console-flush
   #:console-from-file
   #:console-load-asc
   #:console-load-apf
   #:console-save-asc
   #:console-save-apf
   #:console-credits-reset
   #:console-credits-render-ex
   ;; console_init.h
   #:console-is-fullscreen
   ;; console_printing.h
   #:console-set-color-control
   #:console-printf
   #:console-printf-ex
   #:console-printf-rect
   #:console-printf-rect-ex
   #:console-printf-frame
   #:console-get-height-rect-fmt
   #:console-printn
   #:console-printn-rect
   #:console-get-height-rect-n
   #:console-get-height-rect-wn
   ;; misc console print
   #:console-print
   #:console-print-ex
   #:console-print-double-frame
   ;; console_rexpaint.h
   #:console-from-xp
   #:console-load-xp
   #:console-save-xp
   ;; todo
   ;;#:load-xp-from-memory
   ;;#:save-xp-to-memory
   ;;#:load-xp
   ;;#:save-xp
   ;; context.h
   #:context-delete
   #:context-present
   #:context-screen-pixel-to-tile-d
   #:context-screen-pixel-to-tile-i
   #:context-save-screenshot
   #:context-get-sdl-window
   #:context-get-sdl-renderer
   #:context-change-tileset
   #:context-get-renderer-type
   #:context-recommended-console-size
   #:context-screen-capture
   #:context-set-mouse-transform
   ;; context_init.h
   #:context-new
   ;; error.h
   #:get-error
   #:set-error
   #:set-errorf
   #:clear-error
   ;; fov.h
   #:map-new
   #:map-clear
   #:map-copy
   #:map-set-properties
   #:map-delete
   #:map-compute-fov
   #:map-is-in-fov
   #:map-set-in-fov
   #:map-is-transparent
   #:map-is-walkable
   #:map-get-width
   #:map-get-height
   #:map-get-nb-cells
   ;; heightmap.h
   #:heightmap-new
   #:heightmap-delete
   #:heightmap-get-value
   #:heightmap-get-interpolated-value
   #:heightmap-set-value
   #:heightmap-get-slope
   #:heightmap-get-normal
   #:heightmap-count-cells
   #:heightmap-has-land-on-border
   #:heightmap-get-minmax
   #:heightmap-copy
   #:heightmap-add
   #:heightmap-scale
   #:heightmap-clamp
   #:heightmap-normalize
   #:heightmap-clear
   #:heightmap-lerp-hm
   #:heightmap-add-hm
   #:heightmap-multiply-hm
   #:heightmap-add-hill
   #:heightmap-dig-hill
   #:heightmap-dig-bezier
   #:heightmap-rain-erosion
   #:heightmap-kernel-transform
   #:heightmap-add-voronoi
   #:heightmap-mid-point-displacement
   #:heightmap-add-fbm
   #:heightmap-scale-fbm
   ;; image.h
   #:image-new
   #:image-from-console
   #:image-refresh-console
   #:image-clear
   #:image-invert
   #:image-hflip
   #:image-rotate90
   #:image-vflip
   #:image-scale
   #:image-load
   #:image-save
   #:image-get-size
   #:image-get-pixel
   #:image-get-alpha
   #:image-get-mipmap-pixel
   #:image-put-pixel
   #:image-blit
   #:image-blit-rect
   #:image-blit-2x
   #:image-delete
   #:image-set-key-color
   #:image-is-pixel-transparent
   ;; logging.h
   #:set-log-callback
   #:set-log-level
   ;;mersenne.h
   #:random-get-instance
   #:random-new
   #:random-save
   #:random-restore
   #:random-new-from-seed
   #:random-delete
   #:random-set-distribution
   #:random-get-int
   #:random-get-float
   #:random-get-double
   #:random-get-int-mean
   #:random-get-float-mean
   #:random-get-double-mean
   #:random-dice-roll-s
   ;; namegen.h
   #:namegen-parse
   #:namegen-generate
   #:namegen-generate-custom
   #:namegen-get-sets
   #:namegen-destroy
   ;; noise.h
   #:noise-new
   #:noise-set-type
   #:noise-get-ex
   #:noise-get-fbm-ex
   #:noise-get-turbulence-ex
   #:noise-get
   #:noise-get-fbm
   #:noise-get-turbulence
   #:noise-delete
   ;; todo
   ;;#:noise-get-vectorized
   ;;#:noise-get-fbm-vectorized
   ;;#:noise-get-turbulence-vectorized
   ;; path.h
   #:path-new-using-map
   #:path-new-using-function
   #:path-compute
   #:path-walk
   #:path-is-empty
   #:path-size
   #:path-reverse
   #:path-get
   #:path-get-origin
   #:path-get-destination
   #:path-delete
   #:dijkstra-new
   #:dijkstra-new-using-function
   #:dijkstra-compute
   #:dijkstra-get-distance
   #:dijkstra-path-set
   #:dijkstra-is-empty
   #:dijkstra-size
   #:dijkstra-reverse
   #:dijkstra-get
   #:dijkstra-path-walk
   #:dijkstra-delete
   ;; pathfinder.h
   ;; todo
   ;; tileset.h
   #:tileset-new
   #:tileset-delete
   #:tileset-load
   #:tileset-load-mem
   #:tileset-load-raw
   #:tileset-load-raw-2d
   #:tileset-assign-tile
   #:tileset-get-tile
   ;; tileset_bdf.h
   #:load-bdf
   ;; todo #:tileset-load-bdf-memory

   ;; misc helpers
   #:sdl2-event-case
   #:sdl2-scancode-case))
